What is Pandas?

Pandas is a Python library used for working with data. It helps you load, clean, organize, analyze, and manipulate data easily.

Think of Pandas like Excel inside Python, but much more powerful.

For example:

Excel	                  Pandas
Rows & Columns	          Rows & Columns
Filter data	              Filter data
Sort	                  Sort
Formulas	              Calculations
Pivot Table 	          Grouping/Aggregation
Cleaning duplicates	      Data cleaning

Why do Data Analysts use Pandas?

As a data analyst, most of your work is:

Collecting data
Cleaning messy data
Analyzing data
Finding insights
Making reports

Main Uses of Pandas in a Data Analyst Role
1. Reading Data Files

Most companies store data in files like:

CSV /
Excel /
SQL databases /
JSON

Pandas can read them easily.

In [2]:
import pandas as pd

data = pd.read_csv(r"D:\Narendra\Employee_Complete_Dataset.csv")
data

,Employee_number,Employee_name,Employee_age,Maritial_Status,Current_Salary,Number_of_Children,years_experience,past_projects,current_projects,Divorced_earlier,Father_alive,Mother_alive,performance_rating,Education_level,Department,Role,Job_Satisfaction,Work_Life_Balance,is_outlier
0,10001,Karen Anderson,36,True,116138,2,12,6,1,No,Yes,Yes,3,Bachelor's,R&D,Researcher,10.000000,1.936454,0
1,10002,David Taylor,34,False,82171,3,10,5,0,Yes,Yes,No,5,Diploma,HR,HR Executive,10.000000,4.077728,0
2,10003,Nina Kumar,36,False,48600,1,0,2,3,Yes,Yes,Yes,4,Diploma,Sales,Sales Manager,10.000000,3.975622,0
3,10004,John Patel,42,True,39675,1,2,4,2,Yes,Yes,Yes,3,Diploma,Engineering,Software Engineer,1.000000,3.790951,0
4,10005,Emily Sharma,27,True,161304,3,3,11,2,Yes,Yes,Yes,2,High School,R&D,Scientist,8.251833,10.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,59996,Olivia Singh,34,True,30000,1,10,8,2,No,No,Yes,3,Diploma,Support,Customer Specialist,1.620645,10.000000,0
49996,59997,Rohit Anderson,63,False,39817,0,30,5,1,Yes,Yes,Yes,2,Bachelor's,Support,Support Engineer,9.653380,1.826064,0
49997,59998,Olivia Taylor,39,True,30000,0,12,8,3,No,Yes,Yes,2,Diploma,Engineering,ML Engineer,4.690698,2.470172,0
49998,59999,Luke Brown,40,True,50384,1,7,3,2,No,Yes,Yes,3,Bachelor's,Finance,Senior Analyst,1.031014,2.462067,0
49999,60000,Arun Thomas,42,False,115609,2,19,4,1,No,No,Yes,5,Bachelor's,Support,Customer Specialist,8.571629,2.912378,0

In [3]:
data.head(20)

,Employee_number,Employee_name,Employee_age,Maritial_Status,Current_Salary,Number_of_Children,years_experience,past_projects,current_projects,Divorced_earlier,Father_alive,Mother_alive,performance_rating,Education_level,Department,Role,Job_Satisfaction,Work_Life_Balance,is_outlier
0,10001,Karen Anderson,36,True,116138,2,12,6,1,No,Yes,Yes,3,Bachelor's,R&D,Researcher,10.000000,1.936454,0
1,10002,David Taylor,34,False,82171,3,10,5,0,Yes,Yes,No,5,Diploma,HR,HR Executive,10.000000,4.077728,0
2,10003,Nina Kumar,36,False,48600,1,0,2,3,Yes,Yes,Yes,4,Diploma,Sales,Sales Manager,10.000000,3.975622,0
3,10004,John Patel,42,True,39675,1,2,4,2,Yes,Yes,Yes,3,Diploma,Engineering,Software Engineer,1.000000,3.790951,0
4,10005,Emily Sharma,27,True,161304,3,3,11,2,Yes,Yes,Yes,2,High School,R&D,Scientist,8.251833,10.000000,0
5,10006,Leo Patel,38,False,87651,0,8,10,0,No,Yes,Yes,2,Master's,Operations,Operations Coordinator,8.591946,4.097746,0
6,10007,Arun Smith,29,False,76916,1,7,14,3,Yes,No,Yes,3,Bachelor's,R&D,Researcher,9.010214,1.000000,0
7,10008,Aisha Lewis,37,True,62465,1,8,10,2,No,Yes,Yes,2,Master's,R&D,Researcher,4.736449,6.506923,0
8,10009,Arun Thomas,42,True,71206,1,17,4,1,No,Yes,No,3,High School,HR,HR Executive,4.580820,7.338172,0
9,10010,Olivia Thompson,26,True,30000,0,3,4,3,No,Yes,Yes,5,High School,Engineering,DevOps Engineer,1.254238,2.506049,0
10,10011,Olivia Davis,36,True,76188,0,4,13,1,Yes,Yes,Yes,3,Bachelor's,Engineering,DevOps Engineer,10.000000,6.236471,0
11,10012,Luke Iyer,24,False,40313,1,0,7,3,No,No,Yes,4,Diploma,R&D,Scientist,6.378298,7.937918,0
12,10013,Olivia Patel,24,True,37416,0,0,9,0,No,Yes,Yes,5,Master's,Support,Customer Specialist,3.309084,1.000000,0
13,10014,Kiran Lewis,26,True,30000,2,5,6,1,No,Yes,Yes,2,Bachelor's,Support,Customer Specialist,10.000000,1.000000,0
14,10015,Rohit Wilson,40,False,30000,1,7,2,0,No,Yes,Yes,5,Diploma,R&D,Researcher,1.460991,2.692698,0
15,10016,Emily Anderson,54,True,99905,3,16,10,1,No,Yes,Yes,3,Bachelor's,Engineering,DevOps Engineer,6.660381,2.622619,0
16,10017,Rohit Thomas,21,False,80313,2,0,9,2,No,No,Yes,3,Bachelor's,Engineering,DevOps Engineer,9.280978,4.424109,0
17,10018,Michael Williams,33,False,35421,2,3,4,3,Yes,Yes,Yes,3,Bachelor's,Support,Customer Specialist,2.982658,2.004082,0
18,10019,David Smith,47,False,30000,0,22,14,2,No,Yes,Yes,4,High School,Operations,Ops Manager,1.946286,1.245582,0
19,10020,Sarah Lewis,36,True,30000,1,7,9,3,Yes,Yes,Yes,1,Diploma,Operations,Ops Manager,10.000000,1.901731,0

1. Series in Pandas

A Series is a single column of data.

Think of it like one column in Excel.

Example:

In [24]:
s = pd.Series([10, 20, 30, 40])

s

0    10
1    20
2    30
3    40
dtype: int64

In [25]:
s[2]

np.int64(30)

Easy Understanding:

Imagine marks of students:

Marks
10
20
30
40

This single column = Series

Remember:
Series = One Column

Lable Indexing:

In [39]:
a = pd.Series({'a':10,'b':20,'c':30,'d':40,'e':50})
a

a    10
b    20
c    30
d    40
e    50
dtype: int64

two methods of index is there to access the element in lable indexing:
they are, loc and iloc

In [40]:
a.iloc[3]

np.int64(40)

In [44]:
a.loc['c']

np.int64(30)

2. DataFrame in Pandas

A DataFrame is a table with rows and columns.

Think of it like an Excel sheet.

Example:

In [3]:
data = {
    "Name": ["Ram", "Sam", "John"],
    "Age": [22, 24, 21]
}

df = pd.DataFrame(data)

df

   Name  Age
0   Ram   22
1   Sam   24
2  John   21

Easy Understanding:
Name	Age
Ram	    22
Sam	    24
John	21

This whole table = DataFrame

Remember:
DataFrame = Full Table

3. Add Another Column

Suppose we want to add Marks column.

Existing Data:

Name	Age
Ram	    22
Sam	    24

Add new column:

In [4]:
df["Marks"] = [80, 90, 100]

df

   Name  Age  Marks
0   Ram   22     80
1   Sam   24     90
2  John   21    100

Easy Formula: df["New Column"] = values

Example:

df["City"] = ["Chennai", "Coimbatore"]

4. Remove Null Values
What is Null?

Null means missing value.

Example:

Name	Marks
Ram	    80
Sam	    NaN
John	90

Here Sam's marks are missing.

Remove null rows

df.drop_duplicates()

In [8]:
import numpy as np

In [7]:
data = {
    "Name": ["Ram", "Sam", "John"],
    "Marks": [80, np.nan, 90]
}

df = pd.DataFrame(data)

df.dropna()

   Name  Marks
0   Ram   80.0
2  John   90.0

In [4]:
data = {
    "Name": ["Ram", "Sam", "Ram"],
    "Marks": [80, 90, 80]
}

df = pd.DataFrame(data)

df.drop_duplicates()

  Name  Marks
0  Ram     80
1  Sam     90

Duplicate row removed.

Easy Remember:
drop_duplicates()

= Remove repeated rows

Quick Revision
Topic	            Meaning
Series	            One column
DataFrame	        Full table
Add column	        df["column"] = values
Remove null	        dropna()
Remove duplicate	drop_duplicates()

What is fillna() in Pandas?

fillna() is used to fill missing (null/NaN) values instead of removing them.

Remember:

dropna() → removes rows with null values 
fillna() → fills null values

Why do we use fillna()?

Suppose you have this data:

Name	Marks
Ram	    80
Sam	    NaN
John	90

Sam's marks are missing.

If we use: df.dropna()

Sam's entire row gets deleted.

But sometimes we don't want to lose data.

So we use:fillna()

to fill the missing value.

Syntax
df.fillna(value)

value = what you want to replace the missing value with.

Example 1: Fill with 0

In [5]:
data = {
    "Name": ["Ram", "Sam", "John"],
    "Marks": [80, None, 90]
}

df = pd.DataFrame(data)

df.fillna(0)

   Name  Marks
0   Ram   80.0
1   Sam    0.0
2  John   90.0

Easy understanding:

Missing marks became 0.

Example 2: Fill with a specific value

In [6]:
df.fillna(50)

   Name  Marks
0   Ram   80.0
1   Sam   50.0
2  John   90.0

Example 3: Fill only one column

Suppose:

Name	Marks
Ram	    80
Sam	    NaN

Fill only Marks column:

In [9]:
data = {
    "Name": ["Ram", "Sam"],
    "Marks": [80, np.nan]
}

df = pd.DataFrame(data)

df

  Name  Marks
0  Ram   80.0
1  Sam    NaN

In [11]:
df['Marks']=df["Marks"].fillna(50)
df

  Name  Marks
0  Ram   80.0
1  Sam   50.0

In [12]:
df['Marks']=df['Marks'].astype(int)
df

  Name  Marks
0  Ram     80
1  Sam     50

In [29]:
pd.to_numeric(df['Marks'],errors = 'coerce')

0    80.0
1    50.0
Name: Marks, dtype: float64

Only marks column changed.

But dataframe stays same.

To save permanently:

Method 1 (Recommended

df = df.fillna(0)

Method 2

In [33]:
df.fillna(0, inplace=True)

  Name  Marks
0  Ram     80
1  Sam     50

In [34]:
df['Marks']=df['Marks'].astype(int)
df

  Name  Marks
0  Ram     80
1  Sam     50

Now changes are saved in df.

Real-life Data Analyst Example

Imagine salary data:

Name	Salary
A	    50000
B	    NaN
C	    60000

Instead of deleting employee B:

In [59]:
data = {
    "Name": ["A", "B", "C"],
    "Salary": [50000, 'NaN', 60000]
}

df = pd.DataFrame(data)

df.fillna(0)

  Name Salary
0    A  50000
1    B    NaN
2    C  60000

In [62]:
df["Salary"] = df["Salary"].fillna(50000)

You fill missing salary with average/default value.

This is common in data cleaning.

Quick Revision
Function	Work
dropna()	Remove null rows
fillna()	Fill null values
Memory Trick

dropna() → DROP missing data
fillna() → FILL missing data

Example:

df.fillna(0)

1. Concatenate (Combine Data)
What is concatenate?

Concatenate = Joining/Combining datasets

In [2]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Ram", "Sam"],
    "Age": [22, 25]
})

df2 = pd.DataFrame({
    "Name": ["John", "Ravi"],
    "Age": [28, 30]
})

pd.concat([df1, df2])

   Name  Age
0   Ram   22
1   Sam   25
0  John   28
1  Ravi   30